name: shortcut_menu_extender_example
description: "Demonstrates how to use the shortcut_menu_extender plugin."
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shortcut_menu_extender:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
