name: shortcut_menu_extender
description: "This plugin allows Flutter apps to Extending global shortcut menus."
version: 0.1.0
homepage: https://github.com/leanflutter/shortcut_menu_extender

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  shortcut_menu_extender_platform_interface: ^0.1.0
  shortcut_menu_extender_windows: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        default_package: shortcut_menu_extender_windows
